# Generated by Django 5.1.7 on 2025-04-06 02:57

import account.validates
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_picture',
            field=models.ImageField(default='image/default_dp.jpg', upload_to='image/dp/', validators=[account.validates.image_max_res_validate, account.validates.image_max_size_validate]),
        ),
    ]
