# Generated by Django 5.1.7 on 2025-03-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_display_picture_user_is_verify'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_picture',
            field=models.ImageField(blank=True, default=None, upload_to=''),
        ),
    ]
