# Generated by Django 5.2 on 2025-05-16 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_requesttoverify'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestToVerify',
        ),
    ]
