# Generated by Django 5.1.7 on 2025-03-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_user_display_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_picture',
            field=models.ImageField(blank=True, default='image/default_dp.jpg', null=True, upload_to='image/dp/'),
        ),
    ]
