# Generated by Django 5.1.7 on 2025-03-19 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_display_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_picture',
            field=models.ImageField(default='image/default_dp.jpg', upload_to='image/dp/'),
        ),
    ]
