# Generated by Django 5.1.7 on 2025-04-05 14:50

import django.core.validators
import django.db.models.deletion
import product.utlis
import account.validates
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0004_remove_shop_shop_description_gin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_slug', models.SlugField(blank=True)),
                ('description', models.TextField(default='')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('discount_price', models.PositiveIntegerField(default=0)),
                ('stock', models.PositiveIntegerField(default=1)),
                ('is_available', models.BooleanField(default=True)),
                ('cash_on_delivery', models.BooleanField(default=False)),
                ('replacement', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(default='image/default_product.jpg', upload_to=product.utlis.product_image_upload_path, validators=[account.validates.image_max_res_validate, account.validates.image_max_size_validate])),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='product.category')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.shop')),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default='')),
                ('star', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5)])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='product.product')),
            ],
        ),
    ]
