# Generated by Django 5.2 on 2025-04-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_rename_notification_usernotification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='message',
            field=models.TextField(max_length=3000),
        ),
    ]
