# Generated by Django 5.2 on 2025-04-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0003_alter_usernotification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usernotification',
            name='message',
            field=models.TextField(max_length=5000),
        ),
    ]
