# Generated by Django 5.2 on 2025-04-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='message',
            field=models.TextField(max_length=2000),
        ),
    ]
