# Generated by Django 5.1.7 on 2025-03-28 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shop_shop_shop_name_336728_gin'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shop',
            name='shop_shop_name_336728_gin',
        ),
    ]
