# Generated by Django 5.2 on 2025-04-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_owner_shop_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='banner',
            field=models.ImageField(default='image/default_shop_banner.jpg', upload_to='image/shop/banner/'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='logo',
            field=models.ImageField(default='image/default_shop_logo.jpg', upload_to='image/shop/logo/'),
        ),
    ]
