# Generated by Django 5.1.7 on 2025-04-04 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_pinnedshop_user'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shop',
            name='shop_description_gin',
        ),
    ]
