# Generated by Django 5.1.7 on 2025-03-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_shop_shop_name_gin_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='shop',
            name='shop_name_gin_idx',
        ),
    ]
